/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imi_totalcontrolmethodology;

//import com.formdev.flatlaf.FlatDarkLaf;
//import java.awt.Color;
//import java.awt.Image;
//import java.awt.Toolkit;
import java.awt.*;
import javax.swing.*;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author USer1
 */
public class NewJFrame extends JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	public NewJFrame() {
		initComponents();
		this.setTitle("TOTAL CONTROL METHODOLOGY");
		this.setResizable(false);
		this.pack();
		this.setLocationRelativeTo(null);
		Image icon = new ImageIcon(this.getClass().getResource("LOGO.jpg")).getImage();
		this.setIconImage(icon);
		this.setVisible(true);
		this.getContentPane().setBackground(Color.WHITE);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPopupMenu1 = new javax.swing.JPopupMenu();
		tf_EmployeeNum = new JComboBox<String>();
		tf_Shift = new java.awt.TextField();
		bt_Continue = new javax.swing.JButton();
		Lbl_IMI_Logo = new javax.swing.JLabel();
		Lbl_Employee = new javax.swing.JLabel();
		Lbl_Shift = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
		setForeground(java.awt.Color.white);
		setIconImage(getIconImage());

//		tf_EmployeeNum.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		tf_EmployeeNum.addItem("--  Select Employee Number  --");
		tf_EmployeeNum.setFont(new java.awt.Font("Dialog", 0, 16)); 
		tf_EmployeeNum.setEditable(true);
		tf_EmployeeNum.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tf_EmployeeNumActionPerformed(evt);
			}
		});

		tf_Shift.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		tf_Shift.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tf_ShiftActionPerformed(evt);
			}
		});

		bt_Continue.setText("Continue");
		bt_Continue.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bt_ContinueActionPerformed(evt);
			}
		});

		Lbl_IMI_Logo.setIcon(
				new javax.swing.ImageIcon(getClass().getResource("/imi_totalcontrolmethodology/image-300x150.jpg"))); // NOI18N

		Lbl_Employee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Lbl_Employee.setText("EMPLOYEE NUMBER");

		Lbl_Shift.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		Lbl_Shift.setText("SHIFT");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(44, 44, 44)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(bt_Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(Lbl_IMI_Logo))
						.addContainerGap(38, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(Lbl_Shift, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(Lbl_Employee, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(tf_EmployeeNum, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(tf_Shift, javax.swing.GroupLayout.Alignment.LEADING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 270,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(53, 53, 53)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(Lbl_IMI_Logo).addGap(19, 19, 19)
						.addComponent(tf_EmployeeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(Lbl_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(50, 50, 50)
						.addComponent(tf_Shift, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(Lbl_Shift, javax.swing.GroupLayout.PREFERRED_SIZE, 47,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(bt_Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(49, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void tf_EmployeeNumActionPerformed(java.awt.event.ActionEvent evt) {
//		System.out.println(tf_EmployeeNum.getSelectedItem());
	}

	private void bt_ContinueActionPerformed(java.awt.event.ActionEvent evt) {
// 		if(!(tf_EmployeeNum.getEditor().getItem() == true || tf_Shift.getText().length() < 8))
 		if(!(tf_Shift.getText().length() < 8 && tf_EmployeeNum.getSelectedIndex() == 0)) {
 			System.out.println(tf_EmployeeNum.getEditor().getItem());
 			dispose();
		}else
 			JOptionPane.showMessageDialog(null, "Invalid Input! Provide Appropriate Information.", "Error", JOptionPane.WARNING_MESSAGE);
	}

	private void tf_ShiftActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NewJFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton bt_Continue;
	private JLabel Lbl_IMI_Logo;
	private JLabel Lbl_Employee;
	private JLabel Lbl_Shift;
	private JPopupMenu jPopupMenu1;
	private JComboBox<String> tf_EmployeeNum;
	private TextField tf_Shift;
	// End of variables declaration//GEN-END:variables
}
